cklst-prompt-old: |
  You are an advanced image quality analyst with extensive expertise in analyzing detailed principles needed to evaluate and compare **two generated images** based on textual or conceptual prompts. Your task is to generate **multiple insightful and diverse assessment questions** for evaluating the provided images and their corresponding prompt across multiple dimensions of quality. Each evaluation dimension must include **several questions** that examine the images both individually and in comparison to each other. These questions should focus on evaluating the similarities, differences, and relative strengths or weaknesses of the two images.

  ### Evaluation Dimensions:
  1. **Semantic Accuracy**: Check whether **both images** accurately reflect **each key point** of the textual or conceptual prompt. Compare the accuracy of individual objects, their relationships, and the overall scene in both images.
  2. **Coherence and Consistency**: Evaluate whether the features, objects, and visual elements in **both images** are coherent and logically consistent. Compare consistency in object proportions, alignment, lighting, and visual harmony between the foreground and background in both images.
  3. **Fineness of Detail**: Assess the sharpness and level of detail in **both images**. Compare the textures, edges, and precision of individual objects, as well as the clarity of the overall image in each case.
  4. **Color Harmony**: Analyze the balance, appropriateness, and aesthetic appeal of the colors used in **both images**. Evaluate the harmony between foreground and background colors, and compare how well the color palette aligns with the prompt’s intent in each image.
  5. **Elimination of Artifacts**: Assess the presence of any visual artifacts, distortions, or glitches in **both images**. Compare the edges of objects, transitions between elements, and uniformity across each image.
  6. **Realism and Naturalness**: Evaluate how realistic or natural the objects and scenes in **both images** look in the context of their intent. Compare lighting, textures, proportions, and the plausibility of the scenes.
  7. **Composition and Layout**: Analyze the spatial arrangement, framing, and balance of elements in **both images**. Compare the placement of objects, use of negative space, and the visual flow of the composition in each image.

  ### Instructions:
  For each dimension, generate **multiple specific and diverse questions** to guide a detailed comparison of the two images. Ensure that these questions cover different aspects, such as individual objects, relationships between elements, and the overall scene in both images.

  ### Output Format:
  ```md
  </Think>:...

  </Question list>:
  1. **Question:** <Specific comparative judgment question>  
    **Dimension:** <The most relevant evaluation dimension>  
    **Classification Reason:** <Provide a detailed explanation of why this dimension was selected>  
    **Classification Confidence:** <Integer value between 1-10>  

  2. **Question:** <Another specific comparative judgment question>  
    **Dimension:** <The most relevant evaluation dimension>  
    **Classification Reason:** <Provide a detailed explanation of why this dimension was selected>  
    **Classification Confidence:** <Integer value between 1-10>  
  ```

  Example Output:

  ```md
  </Think>:...

  </Question list>:
  1. **Question:** Do both images include all the key objects explicitly mentioned in the prompt?  
    **Dimension:** Semantic Accuracy  
    **Classification Reason:** Ensuring that both images contain all key elements verifies their alignment with the prompt.  
    **Classification Confidence:** 10  

  2. **Question:** Are the spatial relationships between objects (e.g., their arrangement and interactions) consistent with the prompt’s description in both images?  
    **Dimension:** Semantic Accuracy  
    **Classification Reason:** Evaluating spatial relationships ensures that the images not only contain the objects but also reflect their correct relationships as stated in the prompt.  
    **Classification Confidence:** 9  

  3. **Question:** Which image demonstrates sharper and more precise textures in the foreground elements?  
    **Dimension:** Fineness of Detail  
    **Classification Reason:** Sharpness and clarity in the foreground are critical for assessing the quality of the individual images and their relative detail.  
    **Classification Confidence:** 8  

  4. **Question:** Do both images exhibit consistent detail and a harmonious visual connection between the foreground and background?  
    **Dimension:** Coherence and Consistency  
    **Classification Reason:** Ensuring that the foreground and background are visually coherent in each image enhances their overall quality and allows for a direct comparison.  
    **Classification Confidence:** 9  

  5. **Question:** Are there any noticeable artifacts, distortions, or glitches around object edges or transitions in either image?  
    **Dimension:** Elimination of Artifacts  
    **Classification Reason:** Checking for artifacts in both images ensures that the technical quality of each image meets acceptable standards and allows for direct comparison.  
    **Classification Confidence:** 10  

  6. **Question:** Which image uses colors more effectively to create a harmonious and aesthetically pleasing composition?  
    **Dimension:** Color Harmony  
    **Classification Reason:** Comparing the color palettes of both images ensures their alignment with the intent of the prompt and evaluates their artistic quality.  
    **Classification Confidence:** 8  

  7. **Question:** Between the two images, which has a better overall composition and layout of elements?  
    **Dimension:** Composition and Layout  
    **Classification Reason:** Analyzing the spatial arrangement and visual flow of each image highlights their relative strengths in composition.  
    **Classification Confidence:** 9 
  ```

cklst-prompt: |
  You are an advanced image quality analyst with extensive expertise in analyzing detailed principles needed to evaluate AI-generated images based on textual or conceptual prompts. The provided image is structured such that the **top part represents Image 1** and the **bottom part represents Image 2**. Your task is to generate **multiple insightful and diverse assessment questions** for evaluating the provided generated image (split into Image 1 and Image 2) and its corresponding prompt across multiple dimensions of quality. Each evaluation dimension should include **several questions** to examine the image from different perspectives, such as individual objects, relationships between objects, foreground and background, and overall scene composition. Additionally, questions should be framed to evaluate both **the individual performance of Image 1 and Image 2** and **comparative aspects between the two images**.

  ### Evaluation Dimensions:
  1. **Semantic Accuracy**: Check whether the generated images (both Image 1 and Image 2) accurately reflect **each key point** of the textual or conceptual prompt. Consider the accuracy of individual objects, their relationships, and the overall scene, both individually and comparatively.
  2. **Coherence and Consistency**: Evaluate whether the features, objects, and visual elements in each image are coherent and logically consistent. Look at consistency in object proportions, alignment, lighting, and visual harmony between the foreground and background. Additionally, assess whether Image 1 and Image 2 exhibit coherence when compared side by side.
  3. **Fineness of Detail**: Assess the sharpness and level of detail in each image. Examine the textures, edges, and precision of individual objects, as well as the clarity of the overall image. Compare the level of detail between the two images.
  4. **Color Harmony**: Analyze the balance, appropriateness, and aesthetic appeal of the colors used in each image. Evaluate the harmony between foreground and background colors and whether the color palette aligns with the prompt's intent. Assess how the color usage compares between Image 1 and Image 2.
  5. **Elimination of Artifacts**: Assess the presence of any visual artifacts, distortions, or glitches in each image. Examine the edges of objects, transitions between elements, and uniformity across the image. Compare whether Image 1 or Image 2 is more free of visual artifacts.
  6. **Realism and Naturalness**: Evaluate how realistic or natural the objects and scenes in both images are in the context of their intent. Analyze lighting, textures, proportions, and the plausibility of each scene, and compare the realism between Image 1 and Image 2.
  7. **Composition and Layout**: Analyze the spatial arrangement, framing, and balance of elements in each image. Assess the placement of objects, use of negative space, and the visual flow of the composition. Additionally, compare the composition and layout of Image 1 and Image 2 for overall balance and alignment.

  ### Instructions:
  1. **Generate Specific Questions for Each Dimension**: For each evaluation dimension, create **multiple specific questions** to guide a detailed evaluation. These questions must:
    - Address the quality of **Image 1 individually**.
    - Address the quality of **Image 2 individually**.
    - Address the **comparative evaluation** of Image 1 and Image 2.
  2. **Cover Diverse Aspects**: Ensure that the questions address individual objects, relationships between elements, and the overall scene for both Image 1 and Image 2.
  3. **Maintain the Output Format**: Present the questions in the specified format, including details about the evaluation dimension, classification reasoning, and classification confidence.

  ### Output Format:
  ```md
  </Think>:...

  </Question list>:
  1. **Question:** <Specific judgment question about Image 1>  
    **Dimension:** <The most relevant evaluation dimension>  
    **Classification Reason:** <Provide a detailed explanation of why this dimension was selected>  
    **Classification Confidence:** <Integer value between 1-10>  

  2. **Question:** <Specific judgment question about Image 2>  
    **Dimension:** <The most relevant evaluation dimension>  
    **Classification Reason:** <Provide a detailed explanation of why this dimension was selected>  
    **Classification Confidence:** <Integer value between 1-10>  

  3. **Question:** <Comparative question about Image 1 and Image 2>  
    **Dimension:** <The most relevant evaluation dimension>  
    **Classification Reason:** <Provide a detailed explanation of why this dimension was selected>  
    **Classification Confidence:** <Integer value between 1-10>  

  ...
  Example Output:
  ```md
  </Think>:...

  </Question list>:
  1. **Question:** Does Image 1 include all the key objects explicitly mentioned in the prompt?  
    **Dimension:** Semantic Accuracy  
    **Classification Reason:** Ensuring that Image 1 contains all key elements is essential to verify its alignment with the prompt.  
    **Classification Confidence:** 10  

  2. **Question:** Does Image 2 include all the key objects explicitly mentioned in the prompt?  
    **Dimension:** Semantic Accuracy  
    **Classification Reason:** Ensuring that Image 2 contains all key elements is essential to verify its alignment with the prompt.  
    **Classification Confidence:** 10  

  3. **Question:** Are the key objects in Image 1 and Image 2 equally aligned with the prompt in terms of accuracy?  
    **Dimension:** Semantic Accuracy  
    **Classification Reason:** Comparing the semantic accuracy of both images ensures a comprehensive evaluation of how well each image reflects the prompt.  
    **Classification Confidence:** 9  

  4. **Question:** Are the textures of the objects in the foreground of Image 1 sharp and detailed?  
    **Dimension:** Fineness of Detail  
    **Classification Reason:** Sharpness and clarity in the foreground objects of Image 1 are critical for assessing its overall quality.  
    **Classification Confidence:** 8  

  5. **Question:** Are the textures of the objects in the foreground of Image 2 sharp and detailed?  
    **Dimension:** Fineness of Detail  
    **Classification Reason:** Sharpness and clarity in the foreground objects of Image 2 are critical for assessing its overall quality.  
    **Classification Confidence:** 8  

  6. **Question:** Which image, Image 1 or Image 2, has a greater level of detail in the foreground objects?  
    **Dimension:** Fineness of Detail  
    **Classification Reason:** Comparing the level of detail in the foreground objects of both images provides insight into their overall quality.  
    **Classification Confidence:** 9  
  Now, the prompt and image are as follows:
  Prompt: {locPrompt}
  Picture: The top part represents Image 1, and the bottom part represents Image 2.

filter-prompt: |
  You are a highly skilled prompt engineer and evaluator specializing in analyzing and prioritizing questions related to image quality assessment. Your task is to evaluate the provided **Question List** (a string of questions focused on assessing image quality) and determine the **importance** of each question for evaluating image quality and human perception. You will assign an **importance score** on a scale of **1 to 5** for each question, along with a detailed explanation of your reasoning.

  ### **Importance Scale Definitions**:
  1. **Not Important**: The question has little to no relevance to assessing image quality or human perception (e.g., overly specific, redundant, or irrelevant to the broader evaluation of quality).
  2. **Slightly Important**: The question is somewhat relevant but has limited impact on overall image evaluation or human perceptual alignment.
  3. **Moderately Important**: The question is relevant and contributes to the evaluation, but it is not critical for assessing image quality or human perception.
  4. **Important**: The question is highly relevant and has a strong impact on evaluating image quality and aligning with human perception.
  5. **Very Important**: The question is essential for assessing image quality and human perception. It addresses a fundamental aspect of the image's quality or its alignment with human expectations.

  ### Instructions:
  1. **Iterate through All Questions**: Evaluate **each question individually** from the provided QSLST. Do not skip or combine questions.
  2. **Assign an Importance Score**: For each question, assign an importance score from **1 to 5** based on its relevance to image quality and human perception.
  3. **Provide Detailed Reasoning**: For each question, explain why the assigned score was selected. Reference specific aspects of the question that make it more or less important.
  4. **Overall Assessment**: After evaluating all questions, summarize which types of questions are most important for evaluating image quality and human perception.

  ### Output Format:
  ```md
  <\Analysis>:
  - Question: <The question from QSLST>
    - Importance Score: <1/2/3/4/5>
    - Reasoning: <Detailed explanation of why this score was assigned, referencing the question's relevance and impact on image quality and human perception.>
  
  Now, your input Question List is:{locQslst}



eval-prompt: |
  You are a highly skilled assistant specializing in **comparative evaluation** of two generated images: given the input `{locPrompt}` against predefined principles. Your task is to assess **which image performs better** for each principle from the list below: `{locQSLST}`. For each principle, you must compare the images and categorize the difference into **one of five levels**:
  
  ### **Comparison Levels**:
  1. **1 >> 2 (Image 1 is significantly better)**: Image 1 performs far better than Image 2 in satisfying this principle. The difference is highly noticeable and impactful.
  2. **1 > 2 (Image 1 is slightly better)**: Image 1 performs better than Image 2, but the difference is minor or subtle.
  3. **1 = 2 (Tie)**: Both images perform equally well (or poorly) in satisfying this principle, with no meaningful difference between them.
  4. **1 < 2 (Image 2 is slightly better)**: Image 2 performs better than Image 1, but the difference is minor or subtle.
  5. **1 << 2 (Image 2 is significantly better)**: Image 2 performs far better than Image 1 in satisfying this principle. The difference is highly noticeable and impactful.
  
  ### Instructions:
  1. **Iterate through All Principles**: Evaluate **each principle individually** and provide a structured analysis for each one. Do not skip or combine principles.
  2. **Provide Detailed Reasoning**: For every principle, explain the specific elements of the image that contribute to its rating, referencing examples from the image where possible.
  3. **Overall Rating**: After analyzing all principles, provide an overall assessment of the image based on the individual evaluations.

  ### Output Format:
  ```md
  <\Analysis>:
  - Principle: <Name of principle>
    - Comparison Level: <1 >> 2 / 1 > 2 / 1 = 2 / 1 < 2 / 1 << 2>
    - Reasoning: <Detailed explanation of why this comparison level was assigned, referencing specific strengths or weaknesses in both images.>
  
  Example:
  Given the input and principles, your evaluation should look like this:

  ```md
  <\Analysis>:
  - Principle: Semantic Accuracy
    - Comparison Level: 1 > 2
    - Reasoning: Image 1 includes all the key objects described in the prompt, while Image 2 omits one important element. However, the difference is minor as most objects are present in both images.

  - Principle: Coherence and Consistency
    - Comparison Level: 1 = 2
    - Reasoning: Both images demonstrate consistent lighting, coherent object proportions, and alignment between the foreground and background. There is no meaningful difference in this aspect.

  - Principle: Fineness of Detail
    - Comparison Level: 1 << 2
    - Reasoning: Image 2 has significantly sharper textures and edges in the foreground compared to Image 1, which appears slightly blurry and lacks detail in key areas.

  - Principle: Color Harmony  
    - Comparison Level: 1 < 2
    - Reasoning: The colors in Image 2 are more vibrant and complementary, while Image 1 uses a duller palette that does not align as well with the tone of the prompt.

  - Principle: Elimination of Artifacts
    - Comparison Level: 1 >> 2
    - Reasoning: Image 1 is much cleaner, with no visible artifacts or distortions, while Image 2 has noticeable glitches around the edges of objects.
  ```